# Generated by Django 3.1.2 on 2021-01-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('subject', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
