# Generated by Django 3.1.2 on 2021-01-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=1000)),
                ('linkedin', models.CharField(max_length=1000)),
                ('skype', models.CharField(max_length=1000)),
                ('twitter', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=1000)),
                ('linkedin', models.CharField(max_length=1000)),
                ('skype', models.CharField(max_length=1000)),
                ('twitter', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
