# Generated by Django 3.1.2 on 2021-01-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210120_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frontadmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=1000)),
                ('linkedin', models.CharField(max_length=1000)),
                ('skype', models.CharField(max_length=1000)),
                ('twitter', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='app/images')),
            ],
        ),
    ]
